package com.we.fc.project.entity;

import com.we.fc.area.entity.Area;
import com.we.fc.base.BaseEntity;
import com.we.fc.user.entity.DingtalkUser;

import java.io.Serializable;
import java.util.Date;

public class Project extends BaseEntity implements Serializable {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.area_id
     *
     * @mbggenerated
     */
    private Area area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_contact_user_id
     *
     * @mbggenerated
     */
    private DingtalkUser projectContactUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_create_user_id
     *
     * @mbggenerated
     */
    private DingtalkUser projectCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_owner_contact
     *
     * @mbggenerated
     */
    private String projectOwnerContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_owner_contact_tel
     *
     * @mbggenerated
     */
    private String projectOwnerContactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_status
     *
     * @mbggenerated
     */
    private Byte projectStatus;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public Area getArea() {
        return area;
    }

    public void setArea(Area area) {
        this.area = area;
    }

    public DingtalkUser getProjectContactUser() {
        return projectContactUser;
    }

    public void setProjectContactUser(DingtalkUser projectContactUser) {
        this.projectContactUser = projectContactUser;
    }

    public DingtalkUser getProjectCreateUser() {
        return projectCreateUser;
    }

    public void setProjectCreateUser(DingtalkUser projectCreateUser) {
        this.projectCreateUser = projectCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_owner_contact
     *
     * @return the value of project.project_owner_contact
     *
     * @mbggenerated
     */
    public String getProjectOwnerContact() {
        return projectOwnerContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_owner_contact
     *
     * @param projectOwnerContact the value for project.project_owner_contact
     *
     * @mbggenerated
     */
    public void setProjectOwnerContact(String projectOwnerContact) {
        this.projectOwnerContact = projectOwnerContact == null ? null : projectOwnerContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_owner_contact_tel
     *
     * @return the value of project.project_owner_contact_tel
     *
     * @mbggenerated
     */
    public String getProjectOwnerContactTel() {
        return projectOwnerContactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_owner_contact_tel
     *
     * @param projectOwnerContactTel the value for project.project_owner_contact_tel
     *
     * @mbggenerated
     */
    public void setProjectOwnerContactTel(String projectOwnerContactTel) {
        this.projectOwnerContactTel = projectOwnerContactTel == null ? null : projectOwnerContactTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_status
     *
     * @return the value of project.project_status
     *
     * @mbggenerated
     */
    public Byte getProjectStatus() {
        return projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_status
     *
     * @param projectStatus the value for project.project_status
     *
     * @mbggenerated
     */
    public void setProjectStatus(Byte projectStatus) {
        this.projectStatus = projectStatus;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectName=").append(projectName);
        sb.append(", areaId=").append(area);
        sb.append(", projectContactUserId=").append(projectContactUser);
        sb.append(", projectCreateUserId=").append(projectCreateUser);
        sb.append(", projectOwnerContact=").append(projectOwnerContact);
        sb.append(", projectOwnerContactTel=").append(projectOwnerContactTel);
        sb.append(", projectStatus=").append(projectStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}