package com.we.fc.project.entity;

import com.we.fc.base.BaseEntity;

import java.io.Serializable;
import java.util.Date;

public class Project extends BaseEntity implements Serializable {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_contact_user_id
     *
     * @mbggenerated
     */
    private Integer projectContactUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_create_user_id
     *
     * @mbggenerated
     */
    private Integer projectCreateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_owner_contact
     *
     * @mbggenerated
     */
    private String projectOwnerContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_owner_contact_tel
     *
     * @mbggenerated
     */
    private String projectOwnerContactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_status
     *
     * @mbggenerated
     */
    private Byte projectStatus;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.area_id
     *
     * @return the value of project.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.area_id
     *
     * @param areaId the value for project.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_contact_user_id
     *
     * @return the value of project.project_contact_user_id
     *
     * @mbggenerated
     */
    public Integer getProjectContactUserId() {
        return projectContactUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_contact_user_id
     *
     * @param projectContactUserId the value for project.project_contact_user_id
     *
     * @mbggenerated
     */
    public void setProjectContactUserId(Integer projectContactUserId) {
        this.projectContactUserId = projectContactUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_create_user_id
     *
     * @return the value of project.project_create_user_id
     *
     * @mbggenerated
     */
    public Integer getProjectCreateUserId() {
        return projectCreateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_create_user_id
     *
     * @param projectCreateUserId the value for project.project_create_user_id
     *
     * @mbggenerated
     */
    public void setProjectCreateUserId(Integer projectCreateUserId) {
        this.projectCreateUserId = projectCreateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_owner_contact
     *
     * @return the value of project.project_owner_contact
     *
     * @mbggenerated
     */
    public String getProjectOwnerContact() {
        return projectOwnerContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_owner_contact
     *
     * @param projectOwnerContact the value for project.project_owner_contact
     *
     * @mbggenerated
     */
    public void setProjectOwnerContact(String projectOwnerContact) {
        this.projectOwnerContact = projectOwnerContact == null ? null : projectOwnerContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_owner_contact_tel
     *
     * @return the value of project.project_owner_contact_tel
     *
     * @mbggenerated
     */
    public String getProjectOwnerContactTel() {
        return projectOwnerContactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_owner_contact_tel
     *
     * @param projectOwnerContactTel the value for project.project_owner_contact_tel
     *
     * @mbggenerated
     */
    public void setProjectOwnerContactTel(String projectOwnerContactTel) {
        this.projectOwnerContactTel = projectOwnerContactTel == null ? null : projectOwnerContactTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_status
     *
     * @return the value of project.project_status
     *
     * @mbggenerated
     */
    public Byte getProjectStatus() {
        return projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_status
     *
     * @param projectStatus the value for project.project_status
     *
     * @mbggenerated
     */
    public void setProjectStatus(Byte projectStatus) {
        this.projectStatus = projectStatus;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectName=").append(projectName);
        sb.append(", areaId=").append(areaId);
        sb.append(", projectContactUserId=").append(projectContactUserId);
        sb.append(", projectCreateUserId=").append(projectCreateUserId);
        sb.append(", projectOwnerContact=").append(projectOwnerContact);
        sb.append(", projectOwnerContactTel=").append(projectOwnerContactTel);
        sb.append(", projectStatus=").append(projectStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}