package com.we.fc.user.entity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.we.fc.base.BaseEntity;
import com.we.fc.intermediary.entity.Intermediary;
import com.we.fc.menu.entity.Menu;
import com.we.fc.role.entity.Role;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Set;

public class DingtalkUser extends BaseEntity implements UserDetails{


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.tel
     *
     * @mbggenerated
     */
    private String tel;

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public String getPwd() {
        return pwd;
    }

    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.workPlace
     *
     * @mbggenerated
     */
    private String workplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.orgEmail
     *
     * @mbggenerated
     */
    private String orgemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.jobnumber
     *
     * @mbggenerated
     */
    private String jobnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.isHide
     *
     * @mbggenerated
     */
    private Boolean ishide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.isSenior
     *
     * @mbggenerated
     */
    private Boolean issenior;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.interimediary_id
     *
     * @mbggenerated
     */
    private Integer intermediaryId;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dingtalk_user.extattr
     *
     * @mbggenerated
     */
    private String extattr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dingtalk_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.name
     *
     * @return the value of dingtalk_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.name
     *
     * @param name the value for dingtalk_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.position
     *
     * @return the value of dingtalk_user.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.position
     *
     * @param position the value for dingtalk_user.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.mobile
     *
     * @return the value of dingtalk_user.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.mobile
     *
     * @param mobile the value for dingtalk_user.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.tel
     *
     * @return the value of dingtalk_user.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.tel
     *
     * @param tel the value for dingtalk_user.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.workPlace
     *
     * @return the value of dingtalk_user.workPlace
     *
     * @mbggenerated
     */
    public String getWorkplace() {
        return workplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.workPlace
     *
     * @param workplace the value for dingtalk_user.workPlace
     *
     * @mbggenerated
     */
    public void setWorkplace(String workplace) {
        this.workplace = workplace == null ? null : workplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.remark
     *
     * @return the value of dingtalk_user.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.remark
     *
     * @param remark the value for dingtalk_user.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.email
     *
     * @return the value of dingtalk_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.email
     *
     * @param email the value for dingtalk_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.orgEmail
     *
     * @return the value of dingtalk_user.orgEmail
     *
     * @mbggenerated
     */
    public String getOrgemail() {
        return orgemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.orgEmail
     *
     * @param orgemail the value for dingtalk_user.orgEmail
     *
     * @mbggenerated
     */
    public void setOrgemail(String orgemail) {
        this.orgemail = orgemail == null ? null : orgemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.jobnumber
     *
     * @return the value of dingtalk_user.jobnumber
     *
     * @mbggenerated
     */
    public String getJobnumber() {
        return jobnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.jobnumber
     *
     * @param jobnumber the value for dingtalk_user.jobnumber
     *
     * @mbggenerated
     */
    public void setJobnumber(String jobnumber) {
        this.jobnumber = jobnumber == null ? null : jobnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.isHide
     *
     * @return the value of dingtalk_user.isHide
     *
     * @mbggenerated
     */
    public Boolean getIshide() {
        return ishide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.isHide
     *
     * @param ishide the value for dingtalk_user.isHide
     *
     * @mbggenerated
     */
    public void setIshide(Boolean ishide) {
        this.ishide = ishide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.isSenior
     *
     * @return the value of dingtalk_user.isSenior
     *
     * @mbggenerated
     */
    public Boolean getIssenior() {
        return issenior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.isSenior
     *
     * @param issenior the value for dingtalk_user.isSenior
     *
     * @mbggenerated
     */
    public void setIssenior(Boolean issenior) {
        this.issenior = issenior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.interimediary_id
     *
     * @return the value of dingtalk_user.interimediary_id
     *
     * @mbggenerated
     */
    public Integer getIntermediaryId() {
        return intermediaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.interimediary_id
     *
     * @param interimediaryId the value for dingtalk_user.interimediary_id
     *
     * @mbggenerated
     */
    public void setInterimediaryId(Integer interimediaryId) {
        this.intermediaryId = interimediaryId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dingtalk_user.extattr
     *
     * @return the value of dingtalk_user.extattr
     *
     * @mbggenerated
     */
    public String getExtattr() {
        return extattr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dingtalk_user.extattr
     *
     * @param extattr the value for dingtalk_user.extattr
     *
     * @mbggenerated
     */
    public void setExtattr(String extattr) {
        this.extattr = extattr == null ? null : extattr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingtalk_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(this.getId());
        sb.append(", name=").append(name);
        sb.append(", position=").append(position);
        sb.append(", mobile=").append(mobile);
        sb.append(", tel=").append(tel);
        sb.append(", workplace=").append(workplace);
        sb.append(", remark=").append(remark);
        sb.append(", email=").append(email);
        sb.append(", orgemail=").append(orgemail);
        sb.append(", jobnumber=").append(jobnumber);
        sb.append(", ishide=").append(ishide);
        sb.append(", issenior=").append(issenior);
        sb.append(", interimediaryId=").append(intermediaryId);
        sb.append(", createTime=").append(this.getCreateTime());
        sb.append(", updateTime=").append(this.getCreateTime());
        sb.append(", extattr=").append(extattr);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @JsonIgnore
    private Collection<SimpleGrantedAuthority> authorities =new ArrayList<>();

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        List<Role> roles = this.getRoles();
        if (roles.size()>0){
            for (Role role : roles) {
                List<Menu> menus = role.getMenus();
                if (menus.size()>0){
                    for (Menu menu : menus) {
                        String permission = menu.getPermission();
                        if(null==permission||permission.equals("")){
                            permission="no permission";
                        }
                        SimpleGrantedAuthority simpleGrantedAuthority=new SimpleGrantedAuthority(permission);
                        authorities.add(simpleGrantedAuthority);
                    }
                }
            }
        }
        return authorities;
    }

    @Override
    public String getPassword() {
        return this.getPwd();
    }

    @Override
    public String getUsername() {
        return this.getMobile();
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }

    private List<Role> roles;


    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }


    public Set<Menu> getMenus() {
        return menus;
    }

    public void setMenus(Set<Menu> menus) {
        this.menus = menus;
    }

    private Set<Menu> menus;


    public Intermediary getIntermediary() {
        return intermediary;
    }

    public void setIntermediary(Intermediary intermediary) {
        this.intermediary = intermediary;
    }

    private Intermediary intermediary;

}