package com.we.fc.topic.entity;

import com.we.fc.base.BaseEntity;
import com.we.fc.intermediary.entity.Intermediary;
import com.we.fc.user.entity.DingtalkUser;
import org.hibernate.validator.constraints.NotBlank;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.io.Serializable;
import java.util.Date;

public class Topic extends BaseEntity implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.user_id
     *
     * @mbggenerated
     */
    private DingtalkUser user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.intermediary_id
     *
     * @mbggenerated
     */
    @NotNull(message = "中间商不能为空")
    private Intermediary intermediary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_content
     *
     * @mbggenerated
     */
    @NotBlank(message = "跟进内容不能为空")
    private String topicContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic
     *
     * @mbggenerated
     */

    @NotNull(message = "线索状态不能为空")
    private Integer topicStatus;

    private Integer commentsCount;

    public Integer getCommentsCount() {
        return commentsCount;
    }

    public void setCommentsCount(Integer commentsCount) {
        this.commentsCount = commentsCount;
    }

    public Integer getTopicStatus() {
        return topicStatus;
    }

    public void setTopicStatus(Integer topicStatus) {
        this.topicStatus = topicStatus;
    }

    private static final long serialVersionUID = 1L;


    public DingtalkUser getUser() {
        return user;
    }

    public void setUser(DingtalkUser user) {
        this.user = user;
    }

    @Override
    public Intermediary getIntermediary() {
        return intermediary;
    }

    @Override
    public void setIntermediary(Intermediary intermediary) {
        this.intermediary = intermediary;
    }

    public String getTopicContent() {
        return topicContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_content
     *
     * @param topicContent the value for topic.topic_content
     *
     * @mbggenerated
     */
    public void setTopicContent(String topicContent) {
        this.topicContent = topicContent == null ? null : topicContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(user);
        sb.append(", intermediaryId=").append(intermediary);
        sb.append(", topicContent=").append(topicContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}