spring:
 datasource:
  url: jdbc:mysql://47.104.144.238:6666/fc?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
  username: fc
  password: 123456
  driver-class-name: com.mysql.jdbc.Driver
 thymeleaf:
  cache: false
  mode: LEGACYHTML5
 jackson:
  time: GMT+8
  date-format: yyyy-MM-dd HH:mm:ss

mybatis:
 config-location: classpath:mybatis-config.xml
 mapper-locations: classpath:/mapper/**/*.xml
 type-aliases-package: com.jianpanmao.*

server:
 port: 8080
 servlet:
  contextPath: /

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql