package com.we.fc.topicComments.entity;

import com.we.fc.base.BaseEntity;

import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;

public class TopicComments extends BaseEntity implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_comments.topic_id
     *
     * @mbggenerated
     */
    @NotNull(message = "跟进id不能为空")
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_comments.user_id
     *
     * @mbggenerated
     */
    @NotNull(message = "评论人不能为空")
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_comments.topic_comments_content
     *
     * @mbggenerated
     */
    @NotNull(message = "评论内容不能为空")
    private String topicCommentsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic_comments
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_comments.topic_id
     *
     * @return the value of topic_comments.topic_id
     *
     * @mbggenerated
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_comments.topic_id
     *
     * @param topicId the value for topic_comments.topic_id
     *
     * @mbggenerated
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_comments.user_id
     *
     * @return the value of topic_comments.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_comments.user_id
     *
     * @param userId the value for topic_comments.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_comments.topic_comments_content
     *
     * @return the value of topic_comments.topic_comments_content
     *
     * @mbggenerated
     */
    public String getTopicCommentsContent() {
        return topicCommentsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_comments.topic_comments_content
     *
     * @param topicCommentsContent the value for topic_comments.topic_comments_content
     *
     * @mbggenerated
     */
    public void setTopicCommentsContent(String topicCommentsContent) {
        this.topicCommentsContent = topicCommentsContent == null ? null : topicCommentsContent.trim();
    }

}