package com.we.fc.device.entity;

import com.we.fc.base.BaseEntity;
import com.we.fc.intermediary.entity.Intermediary;
import com.we.fc.project.entity.Project;
import com.we.fc.user.entity.DingtalkUser;
import org.hibernate.validator.constraints.NotBlank;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;

public class Device extends BaseEntity implements Serializable {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.operate_user_id
     *
     * @mbggenerated
     */
    private DingtalkUser operateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.transcribe_user_id
     *
     * @mbggenerated
     */
    private DingtalkUser transcribeUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.project_id
     *
     * @mbggenerated
     */
    private Project project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.intermediary_id
     *
     * @mbggenerated
     */
    @NotNull(message = "中间商不能为空")
    private Intermediary intermediary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_production_num
     *
     * @mbggenerated
     */
    @NotBlank(message = "生产编号不能为空")
    @Size(min = 1, max = 20, message = "生成编号在1-20个字符")
    private String deviceProductionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.deivce_status
     *
     * @mbggenerated
     */
    @NotNull(message = "设备状态不能为空")
    private Byte deviceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_location_x
     *
     * @mbggenerated
     */
    @Size(min = 1, max = 20, message = "x坐标在1-20个字符")
    private String deviceLocationX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_location_y
     *
     * @mbggenerated
     */
    @Size(min = 1, max = 20, message = "y坐标在1-20个字符")
    private String deviceLocationY;


    private String deviceType;

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    public DingtalkUser getOperateUser() {
        return operateUser;
    }

    public void setOperateUser(DingtalkUser operateUser) {
        this.operateUser = operateUser;
    }

    public DingtalkUser getTranscribeUser() {
        return transcribeUser;
    }

    public void setTranscribeUser(DingtalkUser transcribeUser) {
        this.transcribeUser = transcribeUser;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public Intermediary getIntermediary() {
        return intermediary;
    }

    public void setIntermediary(Intermediary intermediary) {
        this.intermediary = intermediary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_production_num
     *
     * @return the value of device.device_production_num
     * @mbggenerated
     */
    public String getDeviceProductionNum() {
        return deviceProductionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_production_num
     *
     * @param deviceProductionNum the value for device.device_production_num
     * @mbggenerated
     */
    public void setDeviceProductionNum(String deviceProductionNum) {
        this.deviceProductionNum = deviceProductionNum == null ? null : deviceProductionNum.trim();
    }

    public Byte getDeviceStatus() {
        return deviceStatus;
    }

    public void setDeviceStatus(Byte deviceStatus) {
        this.deviceStatus = deviceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_location_x
     *
     * @return the value of device.device_location_x
     * @mbggenerated
     */
    public String getDeviceLocationX() {
        return deviceLocationX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_location_x
     *
     * @param deviceLocationX the value for device.device_location_x
     * @mbggenerated
     */
    public void setDeviceLocationX(String deviceLocationX) {
        this.deviceLocationX = deviceLocationX == null ? null : deviceLocationX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_location_y
     *
     * @return the value of device.device_location_y
     * @mbggenerated
     */
    public String getDeviceLocationY() {
        return deviceLocationY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_location_y
     *
     * @param deviceLocationY the value for device.device_location_y
     * @mbggenerated
     */
    public void setDeviceLocationY(String deviceLocationY) {
        this.deviceLocationY = deviceLocationY == null ? null : deviceLocationY.trim();
    }


}