package com.we.fc.device.entity;

import com.we.fc.base.BaseEntity;
import com.we.fc.intermediary.entity.Intermediary;
import com.we.fc.project.entity.Project;
import com.we.fc.user.entity.User;

import java.io.Serializable;
import java.util.Date;

public class Device extends BaseEntity implements Serializable {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.operate_user_id
     *
     * @mbggenerated
     */
    private User operateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.transcribe_user_id
     *
     * @mbggenerated
     */
    private User transcribeUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.project_id
     *
     * @mbggenerated
     */
    private Project project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.intermediary_id
     *
     * @mbggenerated
     */
    private Intermediary intermediary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_production_num
     *
     * @mbggenerated
     */
    private String deviceProductionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.deivce_status
     *
     * @mbggenerated
     */
    private Byte deivceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_location_x
     *
     * @mbggenerated
     */
    private String deviceLocationX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_location_y
     *
     * @mbggenerated
     */
    private String deviceLocationY;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    public User getOperateUser() {
        return operateUser;
    }

    public void setOperateUser(User operateUser) {
        this.operateUser = operateUser;
    }

    public User getTranscribeUser() {
        return transcribeUser;
    }

    public void setTranscribeUser(User transcribeUser) {
        this.transcribeUser = transcribeUser;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public Intermediary getIntermediary() {
        return intermediary;
    }

    public void setIntermediary(Intermediary intermediary) {
        this.intermediary = intermediary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_production_num
     *
     * @return the value of device.device_production_num
     *
     * @mbggenerated
     */
    public String getDeviceProductionNum() {
        return deviceProductionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_production_num
     *
     * @param deviceProductionNum the value for device.device_production_num
     *
     * @mbggenerated
     */
    public void setDeviceProductionNum(String deviceProductionNum) {
        this.deviceProductionNum = deviceProductionNum == null ? null : deviceProductionNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.deivce_status
     *
     * @return the value of device.deivce_status
     *
     * @mbggenerated
     */
    public Byte getDeivceStatus() {
        return deivceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.deivce_status
     *
     * @param deivceStatus the value for device.deivce_status
     *
     * @mbggenerated
     */
    public void setDeivceStatus(Byte deivceStatus) {
        this.deivceStatus = deivceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_location_x
     *
     * @return the value of device.device_location_x
     *
     * @mbggenerated
     */
    public String getDeviceLocationX() {
        return deviceLocationX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_location_x
     *
     * @param deviceLocationX the value for device.device_location_x
     *
     * @mbggenerated
     */
    public void setDeviceLocationX(String deviceLocationX) {
        this.deviceLocationX = deviceLocationX == null ? null : deviceLocationX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_location_y
     *
     * @return the value of device.device_location_y
     *
     * @mbggenerated
     */
    public String getDeviceLocationY() {
        return deviceLocationY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_location_y
     *
     * @param deviceLocationY the value for device.device_location_y
     *
     * @mbggenerated
     */
    public void setDeviceLocationY(String deviceLocationY) {
        this.deviceLocationY = deviceLocationY == null ? null : deviceLocationY.trim();
    }


}