package com.we.fc.intermediary.dao;

import com.we.fc.intermediary.entity.Intermediary;
import java.util.List;

public interface IntermediaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intermediary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer intermediaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intermediary
     *
     * @mbggenerated
     */
    int insert(Intermediary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intermediary
     *
     * @mbggenerated
     */
    Intermediary selectByPrimaryKey(Integer intermediaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intermediary
     *
     * @mbggenerated
     */
    List<Intermediary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intermediary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Intermediary record);
}