package com.we.fc.intermediary.entity;

import java.io.Serializable;
import java.util.Date;

public class Intermediary implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_id
     *
     * @mbggenerated
     */
    private Integer intermediaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_name
     *
     * @mbggenerated
     */
    private String intermediaryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_contact
     *
     * @mbggenerated
     */
    private String intermediaryContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_contact_tel
     *
     * @mbggenerated
     */
    private String intermediaryContactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_logo_url
     *
     * @mbggenerated
     */
    private String intermediaryLogoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_create_time
     *
     * @mbggenerated
     */
    private Date intermediaryCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_update_time
     *
     * @mbggenerated
     */
    private Date intermediaryUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_introduction
     *
     * @mbggenerated
     */
    private String intermediaryIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table intermediary
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_id
     *
     * @return the value of intermediary.intermediary_id
     *
     * @mbggenerated
     */
    public Integer getIntermediaryId() {
        return intermediaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_id
     *
     * @param intermediaryId the value for intermediary.intermediary_id
     *
     * @mbggenerated
     */
    public void setIntermediaryId(Integer intermediaryId) {
        this.intermediaryId = intermediaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_name
     *
     * @return the value of intermediary.intermediary_name
     *
     * @mbggenerated
     */
    public String getIntermediaryName() {
        return intermediaryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_name
     *
     * @param intermediaryName the value for intermediary.intermediary_name
     *
     * @mbggenerated
     */
    public void setIntermediaryName(String intermediaryName) {
        this.intermediaryName = intermediaryName == null ? null : intermediaryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_contact
     *
     * @return the value of intermediary.intermediary_contact
     *
     * @mbggenerated
     */
    public String getIntermediaryContact() {
        return intermediaryContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_contact
     *
     * @param intermediaryContact the value for intermediary.intermediary_contact
     *
     * @mbggenerated
     */
    public void setIntermediaryContact(String intermediaryContact) {
        this.intermediaryContact = intermediaryContact == null ? null : intermediaryContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_contact_tel
     *
     * @return the value of intermediary.intermediary_contact_tel
     *
     * @mbggenerated
     */
    public String getIntermediaryContactTel() {
        return intermediaryContactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_contact_tel
     *
     * @param intermediaryContactTel the value for intermediary.intermediary_contact_tel
     *
     * @mbggenerated
     */
    public void setIntermediaryContactTel(String intermediaryContactTel) {
        this.intermediaryContactTel = intermediaryContactTel == null ? null : intermediaryContactTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.area_id
     *
     * @return the value of intermediary.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.area_id
     *
     * @param areaId the value for intermediary.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.user_id
     *
     * @return the value of intermediary.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.user_id
     *
     * @param userId the value for intermediary.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_logo_url
     *
     * @return the value of intermediary.intermediary_logo_url
     *
     * @mbggenerated
     */
    public String getIntermediaryLogoUrl() {
        return intermediaryLogoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_logo_url
     *
     * @param intermediaryLogoUrl the value for intermediary.intermediary_logo_url
     *
     * @mbggenerated
     */
    public void setIntermediaryLogoUrl(String intermediaryLogoUrl) {
        this.intermediaryLogoUrl = intermediaryLogoUrl == null ? null : intermediaryLogoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_create_time
     *
     * @return the value of intermediary.intermediary_create_time
     *
     * @mbggenerated
     */
    public Date getIntermediaryCreateTime() {
        return intermediaryCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_create_time
     *
     * @param intermediaryCreateTime the value for intermediary.intermediary_create_time
     *
     * @mbggenerated
     */
    public void setIntermediaryCreateTime(Date intermediaryCreateTime) {
        this.intermediaryCreateTime = intermediaryCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_update_time
     *
     * @return the value of intermediary.intermediary_update_time
     *
     * @mbggenerated
     */
    public Date getIntermediaryUpdateTime() {
        return intermediaryUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_update_time
     *
     * @param intermediaryUpdateTime the value for intermediary.intermediary_update_time
     *
     * @mbggenerated
     */
    public void setIntermediaryUpdateTime(Date intermediaryUpdateTime) {
        this.intermediaryUpdateTime = intermediaryUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_introduction
     *
     * @return the value of intermediary.intermediary_introduction
     *
     * @mbggenerated
     */
    public String getIntermediaryIntroduction() {
        return intermediaryIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_introduction
     *
     * @param intermediaryIntroduction the value for intermediary.intermediary_introduction
     *
     * @mbggenerated
     */
    public void setIntermediaryIntroduction(String intermediaryIntroduction) {
        this.intermediaryIntroduction = intermediaryIntroduction == null ? null : intermediaryIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intermediary
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", intermediaryId=").append(intermediaryId);
        sb.append(", intermediaryName=").append(intermediaryName);
        sb.append(", intermediaryContact=").append(intermediaryContact);
        sb.append(", intermediaryContactTel=").append(intermediaryContactTel);
        sb.append(", areaId=").append(areaId);
        sb.append(", userId=").append(userId);
        sb.append(", intermediaryLogoUrl=").append(intermediaryLogoUrl);
        sb.append(", intermediaryCreateTime=").append(intermediaryCreateTime);
        sb.append(", intermediaryUpdateTime=").append(intermediaryUpdateTime);
        sb.append(", intermediaryIntroduction=").append(intermediaryIntroduction);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}