package com.we.fc.intermediary.entity;

import com.we.fc.base.BaseEntity;

import java.io.Serializable;
import java.util.Date;

/**
 * 中间商
 */
public class Intermediary extends BaseEntity implements Serializable {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_name
     *
     * @mbggenerated
     */
    private String intermediaryName;   //中间商名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_contact
     *
     * @mbggenerated
     */
    private String intermediaryContact;  //中间商联系人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_contact_tel
     *
     * @mbggenerated
     */
    private String intermediaryContactTel;//中间商联系方式

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;//所属地区

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.user_id
     *
     * @mbggenerated
     */
    private Integer userId;//平台对接人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_logo_url
     *
     * @mbggenerated
     */
    private String intermediaryLogoUrl; //logo url

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intermediary.intermediary_introduction
     *
     * @mbggenerated
     */
    private String intermediaryIntroduction; //图文简介

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table intermediary
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_id
     *
     * @return the value of intermediary.intermediary_id
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_name
     *
     * @return the value of intermediary.intermediary_name
     *
     * @mbggenerated
     */
    public String getIntermediaryName() {
        return intermediaryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_name
     *
     * @param intermediaryName the value for intermediary.intermediary_name
     *
     * @mbggenerated
     */
    public void setIntermediaryName(String intermediaryName) {
        this.intermediaryName = intermediaryName == null ? null : intermediaryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_contact
     *
     * @return the value of intermediary.intermediary_contact
     *
     * @mbggenerated
     */
    public String getIntermediaryContact() {
        return intermediaryContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_contact
     *
     * @param intermediaryContact the value for intermediary.intermediary_contact
     *
     * @mbggenerated
     */
    public void setIntermediaryContact(String intermediaryContact) {
        this.intermediaryContact = intermediaryContact == null ? null : intermediaryContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_contact_tel
     *
     * @return the value of intermediary.intermediary_contact_tel
     *
     * @mbggenerated
     */
    public String getIntermediaryContactTel() {
        return intermediaryContactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_contact_tel
     *
     * @param intermediaryContactTel the value for intermediary.intermediary_contact_tel
     *
     * @mbggenerated
     */
    public void setIntermediaryContactTel(String intermediaryContactTel) {
        this.intermediaryContactTel = intermediaryContactTel == null ? null : intermediaryContactTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.area_id
     *
     * @return the value of intermediary.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.area_id
     *
     * @param areaId the value for intermediary.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.user_id
     *
     * @return the value of intermediary.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.user_id
     *
     * @param userId the value for intermediary.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_logo_url
     *
     * @return the value of intermediary.intermediary_logo_url
     *
     * @mbggenerated
     */
    public String getIntermediaryLogoUrl() {
        return intermediaryLogoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_logo_url
     *
     * @param intermediaryLogoUrl the value for intermediary.intermediary_logo_url
     *
     * @mbggenerated
     */
    public void setIntermediaryLogoUrl(String intermediaryLogoUrl) {
        this.intermediaryLogoUrl = intermediaryLogoUrl == null ? null : intermediaryLogoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intermediary.intermediary_introduction
     *
     * @return the value of intermediary.intermediary_introduction
     *
     * @mbggenerated
     */
    public String getIntermediaryIntroduction() {
        return intermediaryIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intermediary.intermediary_introduction
     *
     * @param intermediaryIntroduction the value for intermediary.intermediary_introduction
     *
     * @mbggenerated
     */
    public void setIntermediaryIntroduction(String intermediaryIntroduction) {
        this.intermediaryIntroduction = intermediaryIntroduction == null ? null : intermediaryIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intermediary
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", intermediaryName=").append(intermediaryName);
        sb.append(", intermediaryContact=").append(intermediaryContact);
        sb.append(", intermediaryContactTel=").append(intermediaryContactTel);
        sb.append(", areaId=").append(areaId);
        sb.append(", userId=").append(userId);
        sb.append(", intermediaryLogoUrl=").append(intermediaryLogoUrl);
        sb.append(", intermediaryIntroduction=").append(intermediaryIntroduction);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}